const { SlashCommandBuilder, PermissionFlagsBits, EmbedBuilder } = require('discord.js');
const { getAnalytics } = require('../systems/analytics');
const { getMemory, getFacts } = require('../ai/memory');
const fs = require('node:fs');
const path = require('node:path');

module.exports = {
  data: new SlashCommandBuilder()
    .setName('jarvis').setDescription('Advanced JARVIS command center.')
    .setDefaultMemberPermissions(PermissionFlagsBits.Administrator).setDMPermission(false)
    .addSubcommand(s=>s.setName('stats').setDescription('Show a live server report.'))
    .addSubcommand(s=>s.setName('diagnostics').setDescription('Run a JARVIS health check.'))
    .addSubcommand(s=>s.setName('permissions').setDescription('Show JARVIS permissions.'))
    .addSubcommand(s=>s.setName('lockdown').setDescription('Lock public text channels.'))
    .addSubcommand(s=>s.setName('unlockdown').setDescription('End emergency lockdown.'))
    .addSubcommand(s=>s.setName('emergency').setDescription('Activate full emergency security protocol.'))
    .addSubcommand(s=>s.setName('security').setDescription('Show security posture.'))
    .addSubcommand(s=>s.setName('analytics').setDescription('Show server analytics.'))
    .addSubcommand(s=>s.setName('automod').setDescription('Toggle AutoMod.').addStringOption(o=>o.setName('mode').setDescription('on, off, or status').setRequired(true).addChoices({name:'on',value:'on'},{name:'off',value:'off'},{name:'status',value:'status'})))
    .addSubcommand(s=>s.setName('antiraid').setDescription('Toggle anti-raid.').addStringOption(o=>o.setName('mode').setDescription('on, off, or status').setRequired(true).addChoices({name:'on',value:'on'},{name:'off',value:'off'},{name:'status',value:'status'})))
    .addSubcommand(s=>s.setName('autorole').setDescription('Configure autorole.').addRoleOption(o=>o.setName('role').setDescription('Role to assign').setRequired(false)))
    .addSubcommand(s=>s.setName('verify').setDescription('Verify yourself.'))
    .addSubcommand(s=>s.setName('case').setDescription('View a moderation case.').addIntegerOption(o=>o.setName('id').setDescription('Case ID').setRequired(true).setMinValue(1)))
    .addSubcommand(s=>s.setName('cases').setDescription('List recent moderation cases.'))
    .addSubcommand(s=>s.setName('audit').setDescription('Show recent audit activity.'))
    .addSubcommand(s=>s.setName('snapshot').setDescription('Create a server configuration snapshot.'))
    .addSubcommand(s=>s.setName('memory').setDescription('Show your JARVIS memory.').addUserOption(o=>o.setName('user').setDescription('Member').setRequired(false)))
    .addSubcommand(s=>s.setName('forget').setDescription('Clear persistent memory.').addUserOption(o=>o.setName('user').setDescription('Member').setRequired(false)))
    .addSubcommand(s=>s.setName('remember').setDescription('Store a persistent fact.').addStringOption(o=>o.setName('fact').setDescription('Fact to remember').setRequired(true)).addUserOption(o=>o.setName('user').setDescription('Member').setRequired(false)))
    .addSubcommand(s=>s.setName('briefing').setDescription('Configure daily briefing.').addStringOption(o=>o.setName('mode').setDescription('on/off').setRequired(false).addChoices({name:'on',value:'on'},{name:'off',value:'off'})).addChannelOption(o=>o.setName('channel').setDescription('Briefing channel').setRequired(false)).addIntegerOption(o=>o.setName('hour').setDescription('Cairo hour 0-23').setMinValue(0).setMaxValue(23)))
    .addSubcommand(s=>s.setName('dashboard').setDescription('Show dashboard status.'))
    .addSubcommandGroup(g=>g.setName('community').setDescription('Community tools.').addSubcommand(s=>s.setName('suggest').setDescription('Create a suggestion.').addStringOption(o=>o.setName('text').setDescription('Suggestion').setRequired(true))).addSubcommand(s=>s.setName('ticket').setDescription('Create a ticket.')).addSubcommand(s=>s.setName('level').setDescription('Show activity level.')).addSubcommand(s=>s.setName('leaderboard').setDescription('Show activity leaderboard.')).addSubcommand(s=>s.setName('rep').setDescription('Give reputation.').addUserOption(o=>o.setName('user').setDescription('Member').setRequired(true))).addSubcommand(s=>s.setName('birthday').setDescription('Save a birthday.').addStringOption(o=>o.setName('date').setDescription('DD-MM').setRequired(true))).addSubcommand(s=>s.setName('giveaway').setDescription('Launch a giveaway.').addIntegerOption(o=>o.setName('seconds').setDescription('Duration').setMinValue(10).setMaxValue(86400)).addStringOption(o=>o.setName('prize').setDescription('Prize').setRequired(true))))
    .addSubcommandGroup(g=>g.setName('fun').setDescription('JARVIS interaction commands.').addSubcommand(s=>s.setName('insult').setDescription('Roast a member.').addUserOption(o=>o.setName('user').setDescription('Target').setRequired(true))).addSubcommand(s=>s.setName('reverse').setDescription('Reverse text.').addStringOption(o=>o.setName('text').setDescription('Text').setRequired(true))).addSubcommand(s=>s.setName('random').setDescription('Generate a random number.').addIntegerOption(o=>o.setName('min').setDescription('Minimum').setRequired(false)).addIntegerOption(o=>o.setName('max').setDescription('Maximum').setRequired(false))).addSubcommand(s=>s.setName('hug').setDescription('Hug a member.').addUserOption(o=>o.setName('user').setDescription('Target').setRequired(true))).addSubcommand(s=>s.setName('slap').setDescription('Slap a member.').addUserOption(o=>o.setName('user').setDescription('Target').setRequired(true))).addSubcommand(s=>s.setName('pat').setDescription('Pat a member.').addUserOption(o=>o.setName('user').setDescription('Target').setRequired(true))).addSubcommand(s=>s.setName('compliment').setDescription('Compliment a member.').addUserOption(o=>o.setName('user').setDescription('Target').setRequired(true))).addSubcommand(s=>s.setName('rate').setDescription('Rate something.').addStringOption(o=>o.setName('thing').setDescription('Thing to rate').setRequired(true)))),

  async execute(interaction, { getConfig, saveConfig, addCase, logEvent }) {
    const sub=interaction.options.getSubcommand(); const guild=interaction.guild; const config=getConfig(guild.id);
    if(sub==='stats') return interaction.reply({embeds:[new EmbedBuilder().setTitle('📊 JARVIS Server Report').setColor(0x00aeff).addFields(
      {name:'Members',value:String(guild.memberCount),inline:true},{name:'Channels',value:String(guild.channels.cache.size),inline:true},{name:'Roles',value:String(guild.roles.cache.size),inline:true},{name:'Cases',value:String(config.cases?.length||0),inline:true},{name:'Warnings',value:String(Object.values(config.warnings||{}).reduce((n,x)=>n+x.length,0)),inline:true},{name:'API',value:`${Math.round(interaction.client.ws.ping)}ms`,inline:true}).setTimestamp()]});
    if(sub==='diagnostics'){const me=guild.members.me,p=me?.permissions;return interaction.reply({embeds:[new EmbedBuilder().setTitle('🩺 JARVIS Diagnostics').setColor(0x00aeff).setDescription([`Status: **ONLINE**`,`API: **${Math.round(interaction.client.ws.ping)}ms**`,`Role position: **${me?.roles.highest?.position??'Unknown'}**`,`AutoMod: **${config.automod.enabled?'ON':'OFF'}**`,`Anti-Raid: **${config.antiRaid.enabled?'ON':'OFF'}**`,`Administrator permission: **${p?.has(PermissionFlagsBits.Administrator)?'YES':'NO'}**`,`AI: **${process.env.GEMINI_API_KEY?'CONFIGURED':'MISSING KEY'}**`].join('\n'))]});}
    if(sub==='permissions'){const p=guild.members.me?.permissions;const names=['Administrator','ManageGuild','ManageChannels','ManageRoles','ManageMessages','KickMembers','BanMembers','ModerateMembers','ViewAuditLog','ManageWebhooks','ModerateMembers'];return interaction.reply({embeds:[new EmbedBuilder().setTitle('🔐 JARVIS Permissions').setColor(0x00aeff).setDescription([...new Set(names)].map(n=>`${p?.has(PermissionFlagsBits[n])?'✅':'❌'} ${n}`).join('\n'))]});}
    if(sub==='lockdown'||sub==='unlockdown'){config.lockdown=sub==='lockdown';saveConfig(guild.id,config);let changed=0;for(const channel of guild.channels.cache.values()){if(!channel.isTextBased()||channel.isThread())continue;if(await channel.permissionOverwrites.edit(guild.roles.everyone,{SendMessages:config.lockdown?false:null}).then(()=>true).catch(()=>false))changed++;}return interaction.reply(`${config.lockdown?'🚨 Emergency lockdown activated':'🔓 Lockdown lifted'}, sir. **${changed}** channels updated.`);}
    if(sub==='emergency'){config.lockdown=true;config.automod.enabled=true;config.antiRaid.enabled=true;config.antiRaid.lockdown=true;saveConfig(guild.id,config);let changed=0;for(const channel of guild.channels.cache.values()){if(!channel.isTextBased()||channel.isThread())continue;if(await channel.permissionOverwrites.edit(guild.roles.everyone,{SendMessages:false}).then(()=>true).catch(()=>false))changed++;}const c=addCase(guild.id,{action:'EMERGENCY-LOCKDOWN',userId:interaction.user.id,moderatorId:interaction.client.user.id,reason:'Manual JARVIS emergency protocol'});await logEvent(guild,`🚨 **JARVIS EMERGENCY PROTOCOL** activated by **${interaction.user.tag}** — ${changed} channels secured — Case #${c.id}`);return interaction.reply(`🚨 **Emergency protocol activated, sir.**\nSecured **${changed}** channels. AutoMod and Anti-Raid are now online. Case **#${c.id}** created.`);}
    if(sub==='security'){const recent=(config.cases||[]).filter(c=>String(c.action||'').includes('SECURITY')||String(c.action||'').includes('AUTOMOD')).slice(-10).reverse();return interaction.reply(`🛡️ **JARVIS Security Status**\nAutoMod: **${config.automod.enabled?'ONLINE':'OFFLINE'}**\nAnti-Raid: **${config.antiRaid.enabled?'ONLINE':'OFFLINE'}**\nAnti-Nuke: **${config.security?.antiNuke!==false?'ONLINE':'OFFLINE'}**\nLockdown: **${config.lockdown?'ACTIVE':'CLEAR'}**\nRecent security cases: **${recent.length}**`);}
    if(sub==='analytics'){const a=getAnalytics(guild.id);return interaction.reply(`📊 **JARVIS Analytics**\nMessages observed: **${a.totalMessages}**\nTop members: ${a.topUsers.length?a.topUsers.map(x=>`<@${x.userId}> — ${x.count}`).join(' · '):'No activity yet.'}`);}
    if(sub==='automod'||sub==='antiraid'){const mode=interaction.options.getString('mode');if(sub==='automod')config.automod.enabled=mode==='on'?true:mode==='off'?false:config.automod.enabled;else config.antiRaid.enabled=mode==='on'?true:mode==='off'?false:config.antiRaid.enabled;saveConfig(guild.id,config);const value=sub==='automod'?config.automod.enabled:config.antiRaid.enabled;return interaction.reply(`${sub==='automod'?'🛡️ AutoMod':'🚨 Anti-Raid'} is **${value?'ONLINE':'OFFLINE'}**.`);}
    if(sub==='autorole'){const role=interaction.options.getRole('role');if(!role)return interaction.reply(`🎭 Autorole: ${config.autoroleId?`<@&${config.autoroleId}>`:'Not configured'}.`);config.autoroleId=role.id;saveConfig(guild.id,config);return interaction.reply(`✅ Autorole set to **${role.name}**.`);}
    if(sub==='verify'){if(!config.verificationRoleId)return interaction.reply({content:'❌ Verification has not been configured.',ephemeral:true});const role=guild.roles.cache.get(config.verificationRoleId);if(!role)return interaction.reply({content:'❌ Verification role no longer exists.',ephemeral:true});if(interaction.member.roles.cache.has(role.id))return interaction.reply({content:"✅ You're already verified, sir.",ephemeral:true});try{await interaction.member.roles.add(role,'JARVIS verification');return interaction.reply(`✅ Verification complete, ${interaction.member}.`);}catch{return interaction.reply({content:"❌ I couldn't assign the verification role.",ephemeral:true});}}
    if(sub==='case'){const id=interaction.options.getInteger('id');const entry=(config.cases||[]).find(c=>c.id===id);if(!entry)return interaction.reply({content:'❌ Case not found.',ephemeral:true});return interaction.reply({embeds:[new EmbedBuilder().setTitle(`📁 Case #${id}`).setColor(0x00aeff).addFields({name:'Action',value:entry.action||'Unknown',inline:true},{name:'User',value:entry.userId?`<@${entry.userId}>`:'Unknown',inline:true},{name:'Moderator',value:entry.moderatorId?`<@${entry.moderatorId}>`:'Unknown',inline:true},{name:'Reason',value:entry.reason||'No reason provided'},{name:'Time',value:`<t:${Math.floor(new Date(entry.at).getTime()/1000)}:F>`})]});}
    if(sub==='cases'){const rows=(config.cases||[]).slice(-15).reverse();return interaction.reply({embeds:[new EmbedBuilder().setTitle('📁 Recent Cases').setColor(0x00aeff).setDescription(rows.length?rows.map(c=>`**#${c.id}** ${c.action} — <@${c.userId}> — ${c.reason||'No reason'}`).join('\n'):'No cases recorded.')]});}
    if(sub==='audit'){const logs=await guild.fetchAuditLogs({limit:10}).catch(()=>null);if(!logs)return interaction.reply({content:"❌ I couldn't read the audit log.",ephemeral:true});const lines=logs.entries.map(e=>`**${e.action}** — ${e.executor?.tag||'Unknown'} — <t:${Math.floor(e.createdTimestamp/1000)}:R>`).slice(0,10);return interaction.reply({embeds:[new EmbedBuilder().setTitle('🔎 Recent Audit Activity').setDescription(lines.join('\n')||'No entries.').setColor(0x00aeff)]});}
    if(sub==='snapshot'){const snapshot={generatedAt:new Date().toISOString(),guildId:guild.id,guildName:guild.name,memberCount:guild.memberCount,channels:guild.channels.cache.map(c=>({id:c.id,name:c.name,type:c.type,parentId:c.parentId})),roles:guild.roles.cache.map(r=>({id:r.id,name:r.name,position:r.position,color:r.hexColor})),config};const file=path.join(__dirname,'..','..','data',`${guild.id}-snapshot-${Date.now()}.json`);fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,JSON.stringify(snapshot,null,2));return interaction.reply(`📦 Snapshot created: **${snapshot.channels.length} channels**, **${snapshot.roles.length} roles**.`);}
    if(sub==='memory'){const u=interaction.options.getUser('user')||interaction.user;const mem=getMemory(config,guild.id,u.id);const facts=getFacts(config,guild.id,u.id);return interaction.reply(`🧠 **Memory for ${u.tag}**\nConversation entries: **${mem.length}**\nLong-term facts: **${facts.length}**\n${facts.length?facts.map(x=>`• ${x.text}`).join('\n'):'No long-term facts stored.'}`.slice(0,1900));}
    if(sub==='forget'){const u=interaction.options.getUser('user')||interaction.user;delete config.ai?.facts?.[guild.id]?.[u.id];delete config.ai?.memory?.[guild.id]?.[u.id];saveConfig(guild.id,config);return interaction.reply(`🧹 Memory cleared for **${u.tag}**, sir.`);}
    if(sub==='remember'){const u=interaction.options.getUser('user')||interaction.user;const fact=interaction.options.getString('fact');config.ai.facts??={};config.ai.facts[guild.id]??={};config.ai.facts[guild.id][u.id]??=[];config.ai.facts[guild.id][u.id].push({text:fact.slice(0,300),at:new Date().toISOString()});config.ai.facts[guild.id][u.id]=config.ai.facts[guild.id][u.id].slice(-40);saveConfig(guild.id,config);return interaction.reply(`🧠 Stored a long-term memory for **${u.tag}**, sir.`);}
    if(sub==='briefing'){const mode=interaction.options.getString('mode');const ch=interaction.options.getChannel('channel');const hour=interaction.options.getInteger('hour');if(mode==='off'){config.ai.dailyBriefing.enabled=false;}else{config.ai.dailyBriefing.enabled=true;if(ch)config.ai.dailyBriefing.channelId=ch.id;if(hour!==null)config.ai.dailyBriefing.hour=hour;if(!config.ai.dailyBriefing.channelId)config.ai.dailyBriefing.channelId=interaction.channel.id;}saveConfig(guild.id,config);return interaction.reply(`📋 Daily briefing **${config.ai.dailyBriefing.enabled?'enabled':'disabled'}**${config.ai.dailyBriefing.enabled?` in <#${config.ai.dailyBriefing.channelId}> at ${config.ai.dailyBriefing.hour}:00 Cairo time`:''}, sir.`);}
    if(sub==='community'){
      const action=interaction.options.getSubcommand();
      if(action==='suggest'){const text=interaction.options.getString('text');const sent=await interaction.channel.send({embeds:[new EmbedBuilder().setTitle('💡 JARVIS Suggestion').setDescription(text).addFields({name:'Author',value:`${interaction.user}`}).setTimestamp()]});await sent.react('👍').catch(()=>{});await sent.react('👎').catch(()=>{});return interaction.reply('✅ Suggestion recorded, sir.');}
      if(action==='ticket'){const ch=await guild.channels.create({name:`ticket-${interaction.user.username}`.toLowerCase().replace(/[^a-z0-9-]/g,'-').slice(0,70),type:0,permissionOverwrites:[{id:guild.roles.everyone.id,deny:[PermissionFlagsBits.ViewChannel]},{id:interaction.user.id,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages,PermissionFlagsBits.ReadMessageHistory]},{id:guild.members.me.id,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages,PermissionFlagsBits.ReadMessageHistory]}]}).catch(()=>null);return interaction.reply(ch?`🎫 Ticket created: ${ch}`:'❌ I could not create the ticket, sir.');}
      if(action==='level'||action==='leaderboard'){const a=getAnalytics(guild.id);return interaction.reply(action==='level'?`⭐ Your observed messages: **${a.topUsers.find(x=>x.userId===interaction.user.id)?.count||0}** · Rank: **${a.topUsers.findIndex(x=>x.userId===interaction.user.id)+1||'Unranked'}**`:`🏆 **Activity Leaderboard**
${a.topUsers.map((x,i)=>`${i+1}. <@${x.userId}> — ${x.count}`).join('\n')||'No activity yet.'}`);}
      if(action==='rep'){const u=interaction.options.getUser('user');config.rep??={};config.rep[u.id]=(config.rep[u.id]||0)+1;saveConfig(guild.id,config);return interaction.reply(`⭐ ${u} now has **${config.rep[u.id]}** JARVIS reputation.`);}
      if(action==='birthday'){const date=interaction.options.getString('date');if(!/^\d{2}-\d{2}$/.test(date))return interaction.reply({content:'❌ Use DD-MM.',ephemeral:true});config.birthdays??={};config.birthdays[interaction.user.id]=date;saveConfig(guild.id,config);return interaction.reply(`🎂 Birthday saved as **${date}**, sir.`);}
      if(action==='giveaway'){const seconds=interaction.options.getInteger('seconds')||60;const prize=interaction.options.getString('prize');const sent=await interaction.channel.send(`🎉 **JARVIS GIVEAWAY**\nPrize: **${prize}**\nReact with 🎉 within **${seconds}s**.`);await sent.react('🎉').catch(()=>{});setTimeout(async()=>{const fresh=await sent.fetch().catch(()=>null);const reaction=fresh?.reactions.cache.get('🎉');const users=reaction?await reaction.users.fetch():new Map();const entrants=[...users.values()].filter(u=>!u.bot);const winner=entrants[Math.floor(Math.random()*entrants.length)];await interaction.channel.send(winner?`🏆 Congratulations ${winner}! You won **${prize}**.`:`No valid entrants for **${prize}**, sir.`).catch(()=>{});},seconds*1000);return interaction.reply('🎉 Giveaway launched, sir.');}
    }
    if(sub==='fun'){
      const fun=interaction.options.getSubcommand(); const u=interaction.options.getUser('user');
      if(fun==='insult'){ if(!u) return interaction.reply({content:'❌ Choose a target, sir.',ephemeral:true}); if(u.id===interaction.user.id||u.id===process.env.JARVIS_OWNER_ID)return interaction.reply('Nice try, sir. I shall direct the criticism elsewhere.'); return interaction.reply(`Certainly, sir. **${u.tag}**, your personality appears to be running on a trial version.`); }
      if(fun==='reverse') return interaction.reply((interaction.options.getString('text')||'').split('').reverse().join(''));
      if(fun==='random'){let min=interaction.options.getInteger('min')??1,max=interaction.options.getInteger('max')??100;if(min>max)[min,max]=[max,min];return interaction.reply(`🎲 **${Math.floor(Math.random()*(max-min+1))+min}**`);}
      if(['hug','slap','pat','compliment'].includes(fun)) return interaction.reply(`**${interaction.user}** ${fun==='hug'?'🤗 hugs':fun==='slap'?'👋 slaps':fun==='pat'?'🫳 pats':'💙 compliments'} **${u||'them'}**.`);
      if(fun==='rate') return interaction.reply(`I'd rate **${interaction.options.getString('thing')}** a very respectable **${Math.floor(Math.random()*101)}/100**, sir.`);
    }
    if(sub==='dashboard')return interaction.reply(`🖥️ Dashboard: **${String(process.env.DASHBOARD_ENABLED||'false').toLowerCase()==='true'?'ONLINE':'DISABLED'}**. ${process.env.DASHBOARD_ENABLED==='true'?'It is served by Railway on the configured PORT.':''}`);
  }
};
